# [Lab] Hidden Markov Model (HMM)
###### *Pr : Jae Yun JUN KIM* 
######Date : *August 20, 2019*


## I. Task 

#### 1. Implement yourself the HMM algorithm to solve the evaluation and decoding problems for the Example given in class.

##### Partie cours

The HMM algorithm is based on the Markov's property saying that : 

> "The future is independent from the past given the present"

$Z(0) \rightarrow Z(1) \rightarrow Z(2) \rightarrow ... \rightarrow Z(t-1) \rightarrow Z(t) \rightarrow Z(t+1)$

$Z(t)$ is a hidden state at time $t$



##### Partie code

In [0]:
# import Librairies
import numpy as np
import random as rd 
import matplotlib.pyplot as plt

In [0]:
# Initialize transition probability and emission propability matrix
a_ = np.array([[1,0,0,0],[0.2,0.3,0.1,0.4],[0.2,0.5,0.2,0.1],[0.7,0.1,0.1,0.1]])
b_ = np.array([[1,0,0,0,0], [0,0.3,0.4,0.1,0.2], [0,0.1,0.1,0.7,0.1], [0,0.5,0.2,0.1,0.2]])
X_ = np.array([1,3,2,0])
X_til_ = np.array([0,1,2,3,4])
Z_til_ = np.array([0,1,2,3])

In [0]:
print("a : \n", a_, "\n\nb : \n", b_, "\n\nX : \n", X_, \
      "\n\nPossible Xs : \n", X_til_, "\n\nPossible Zs : \n", Z_til_)

a : 
 [[1.  0.  0.  0. ]
 [0.2 0.3 0.1 0.4]
 [0.2 0.5 0.2 0.1]
 [0.7 0.1 0.1 0.1]] 

b : 
 [[1.  0.  0.  0.  0. ]
 [0.  0.3 0.4 0.1 0.2]
 [0.  0.1 0.1 0.7 0.1]
 [0.  0.5 0.2 0.1 0.2]] 

X : 
 [1 3 2 0] 

Possible X : 
 [0 1 2 3 4] 

Possible Z : 
 [0 1 2 3]


In [0]:
class hidden_markov():
  def __init__(self, a=None, b=None, Z_til=None, X_til=None, X=None, verbose=False):
    # Transition probability matrix
    self.a = a
    # Emission probability matrix
    self.b = b
    # Z and X matrix
    self.Z = np.zeros(X.shape[0]+1)
    self.X = X
    # Possible Z and X
    self.Z_til=Z_til
    self.X_til=X_til
    #verbosity level
    self.alphas = np.zeros([self.Z_til.shape[0], self.Z.shape[0]])

    self.verbose = verbose

  def initialize_first_z(self):
    self.Z[0] = 1
    self.alphas[int(self.Z[0]), 0] = 1

  def evaluate(self):
    self.initialize_first_z()
    
    if self.verbose : print("Initial Z=", self.Z[0], "\nAlphas : ", self.alphas)
    
    for t in range(self.Z.shape[0]):
      if t>0: 
        self.calculate_alphas(t)
        np.set_printoptions(suppress=True)
        if self.verbose : print("At time ", t, " | Z=", self.Z[t], " | X=", self.X[t-1], \
                                "\nalphas = \n", self.alphas)
        

    print("This scenario has : {} chances to happen.".format(self.alphas[0,4]))
  
  def calculate_alphas(self,t):
      x_at_time_t = int(self.X[t-1])
      for z in self.Z_til:
        for z_t_1 in self.Z_til:
          z, z_t_1 = int(z), int(z_t_1)
          self.alphas[z, t] += self.alphas[z_t_1, t-1]*self.a[z_t_1,z]*self.b[z,x_at_time_t]


  def decode(self):

    maxInColumns = np.amax(self.alphas, axis=0)

    for t in range(self.Z.shape[0]):
      
      Z = np.where(self.alphas[:,t] == maxInColumns[t])[0][0]
      print("At time ", t, " | Z=", Z, " | X=", self.X[t-1])
      self.Z[t]=Z

    print("most probable Z : ", self.Z)
    print('Max value of every column: ', maxInColumns)




In [0]:
c = hidden_markov(a=a_, b=b_, X_til=X_til_, Z_til=Z_til_, X=X_, verbose=True)

In [0]:
c.evaluate()

Initial Z= 1.0 
Alphas :  [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
At time  1  | Z= 0.0  | X= 1 
alphas = 
 [[0.   0.   0.   0.   0.  ]
 [1.   0.09 0.   0.   0.  ]
 [0.   0.01 0.   0.   0.  ]
 [0.   0.2  0.   0.   0.  ]]
At time  2  | Z= 0.0  | X= 3 
alphas = 
 [[0.     0.     0.     0.     0.    ]
 [1.     0.09   0.0052 0.     0.    ]
 [0.     0.01   0.0217 0.     0.    ]
 [0.     0.2    0.0057 0.     0.    ]]
At time  3  | Z= 0.0  | X= 2 
alphas = 
 [[0.     0.     0.     0.     0.    ]
 [1.     0.09   0.0052 0.0052 0.    ]
 [0.     0.01   0.0217 0.0005 0.    ]
 [0.     0.2    0.0057 0.001  0.    ]]
At time  4  | Z= 0.0  | X= 0 
alphas = 
 [[0.     0.     0.     0.     0.0018]
 [1.     0.09   0.0052 0.0052 0.    ]
 [0.     0.01   0.0217 0.0005 0.    ]
 [0.     0.2    0.0057 0.001  0.    ]]
This scenario has : 0.0018218000000000002 chances to happen.


In [0]:
c.decode()

At time  0  | Z= 1  | X= 0
At time  1  | Z= 3  | X= 1
At time  2  | Z= 2  | X= 3
At time  3  | Z= 1  | X= 2
At time  4  | Z= 0  | X= 0
most probable Z :  [1. 3. 2. 1. 0.]
Max value of every column:  [1.     0.2    0.0217 0.0052 0.0018]
